@php
    $faqs = [
        ['question' => '1. How Do I Know Which Course Is Right for Me?', 'answer' => 'At WTS Visa Consultancy, we know that choosing the right course is crucial for your success in the future. To help you find the course that fits you best, we need to evaluate your strengths, interests, and career goals. Upon evaluation, investigate the location and industry demand for the career you best online schools for transferring credits want to take up. Our expert career counsellors help you take career assessment tests and discuss possibilities with you. Understanding the course structure content and learning outcomes complements your informed choice. The more you align your interests with career opportunities, the more satisfied and stable you become in the long term regarding your career.'],
         ['question' => '2.	After Enrolment, Can I Change My Course?', 'answer' => 'Yes, institutions permit course change in a specified time, but in some cases transferring the credits could become necessary and complying with new admission requirements might be an obligation too. In the case of such changes, understand the ramifications of the transition with the help of our team at WTS Visa Consultancy. Some of the changes might require an extra fee or an extended period of study make it worthwhile to think through your decision carefully. We work very closely with the institutions to ensure a smooth transition. '],
        ['question' => '3.	Which Courses Have the Most Job Demand?', 'answer' => 'According to job statistics today, the highest job demand for courses belongs to technology, healthcare, and business. Artificial Intelligence, data science, nursing, and digital marketing fields offer strong job opportunities and competitive pay packages. At WTS Visa Consultancy, we always stay the best online bachelors degree updated on market trends and industry development so we can help you choose high-demand courses that give stability to your career and maximize your earning potential. Our consultants will guide you specifically based on your situation to ensure that you choose a course with bright career prospects.'],
        ['question' => '4.	What Are Short-Term Courses? Are they Worth it?', 'answer' => 'Short-term courses provide a fast track to skills and readiness. Their duration varies between a few weeks and few months and are geared towards specialized skills. Such courses would help one gain a few extra qualifications in advancing their career or basically exploring them. These courses arent too thorough, but they offer quick employment. At WTS Visa Consultancy, we help you find the right short-term course to expedite your career or transition to a new industry in a very cost-effective way. '],
        ['question' => '5. Financial Aid for My Course? How to Apply?', 'answer' => 'Various forms of financial aid are available that include scholarships, grants, student loans, and work-study programs. At WTS Visa Consultancy, we assist you in identifying suitable funding options and applying for them. We guide you in understanding the terms and conditions for repayment so that you are able to manage your finances. Complete the financial aid application as soon as possible, as the earliest a few students apply, the later the decision on their applications can be made. With the help of our experts, you can get the funding required to proceed with your studies without financial worries.'],
    ];
@endphp

<x-faq :faqs="$faqs" />