@php
    $faqs = [
         ['question' => '1. Do You Provide SOP Assistance for All Countries?', 'answer' => 'Yes, at WTS Visa Consultancy, SOP assistance for all major study destinations like the USA, Canada, UK, Australia, and Europe, is what we provide. Our well-experienced consultants fully understand the specific guidelines and what the universities or the visa offices at separate countries expect from personal statement help individual applicants. The content gets to be tailored accordingly; hence, it reflects the cultural standards and academics of that particular region. We make sure your SOP aligns perfectly with the specified requirements of your target institution.'],
         ['question' => '2.	How Long Does it Take to Get My SOP Written?', 'answer' => 'The time to do an SOP accounts thus much for the complexity of a profile and the application needs. Generally, a fully written SOP will take about 3 to 5 working days. We also have an urgent service if you wish to meet the application deadline without compromising quality when urgently needed. '],
         ['question' => '3.	Is the SOP Plagiarism-Free and Unique?', 'answer' => 'Yes, all our SOPs are completely original, plagiarism-free. Every SOP is written by us from the ground up on your profile, best sop writers goals, and motivations. We research our subjects and apply high-end plagiarism detectors to guarantee that the end product is 100% unique and authentic.'],
         ['question' => '4.	Can I Ask for Revision Once I Receive My SOP? ', 'answer' => 'Yes, our revisions are free of charge so you can be assured that the final SOP will be satisfactory. If you need any alterations or clarifications, you may request for revisions within a certain present number of days from the delivery date. That is what we want to offer - an SOP that is satisfactory and strengthens your application. '],
        ['question' => '6. What Is the Cost of SOP Assistance? ', 'answer' => 'As such our SOP assistance cost and charges differ based on how complicated the document is and the urgency of the proposal. Our prices are competitive and flexible packages cater to different personal statement writer budgets and needs. Our fees, however, reflect the quality and expertise embodying the making of one professional SOP.'],
    ];
@endphp

<x-faq :faqs="$faqs" />