@php
    $faqs = [
        ['question' => '1. Who Can Apply for an Education Loan?', 'answer' => 'Any Indian student who wants to study abroad can apply for an education loan. Most banks and financial institutions require the applicant to have a confirmed admission to a foreign university. A co-applicant—usually a parent or guardian—is required to support the application. Academic records such as past transcripts and entrance test scores are reviewed.'],
        ['question' => '2.	Can I Get a Loan without Collateral?', 'answer' => 'Yes, you can get a loan without pledging collateral. These are called unsecured or non-collateral education loans. Lenders evaluate various factors before giving such loans including the reputation of the university, the course you have chosen and the credit profile and financial standing of the co-applicant. We help you identify the best lender for your profile to get an education loan without collateral.'],
        ['question' => '3.	How Long Does it Take to Get the Loan Approved?', 'answer' => 'Loan approval process takes 7 to 15 working days depending on the completeness of documents and internal processing time of the lender. With our dedicated guidance and assistance the documentation process becomes seamless and faster. We ensure all your documents are in order from the beginning so that there are no delays.'],
        ['question' => '4.	Will My Visa Application be affected by the Loan?', 'answer' => 'No, an education loan does not affect your visa application. In fact having a loan approved strengthens your visa file as it clearly shows your financial preparedness to support your education abroad. Immigration authorities consider proof of funding as an important part of the student visa process. When you include your loan sanction letter in your visa application it serves as strong evidence that you have sufficient funds to cover tuition and living expenses. Many students get their visas with education loans from recognized lenders.'],
        ['question' => '5. Can I Apply for a Loan before Getting My Offer Letter?', 'answer' => 'Yes, you can start your education loan process even before getting your offer letter. Many lenders offer conditional approval based on your academic performance, entrance exam scores and the course or university you are planning to join. This early approval can be very helpful as it helps you plan your finances and stay ahead of visa timelines.'],
    ];
@endphp

<x-faq :faqs="$faqs" />