@php
    $faqs = [
        ['question' => '1. Can I Book a Flight Ticket without Paying for it?', 'answer' => 'Yes, you can book a dummy flight ticket without a full payment. We at WTS Visa Consultancy offer dummy flight tickets that are to be used as proof of travel for the purpose of visa application. A Dummy ticket contains all details of a flight including departure date and time and destination which are acceptable to an embassy. These tickets are usable for a few days and can be refunded without any penalty so you can fulfil visa requirements without the financial burden of a booked ticket. Our experts ensure all flight information coincides with your travel schedule to minimize the risk of visa refusal.'],
        ['question' => '2.	What Is a Dummy Hotel Booking, and Is it Accepted for Visa Applications?', 'answer' => 'A dummy hotel reservation is a temporary booking used as evidence of accommodation for visa purposes. It has a hotel name, location and stay duration. Embassies will usually accept dummy bookings as genuine evidence if the information is correct and matches your travel plan. Dummy bookings are useful because it satisfies visa requirements without needing a non-refundable deposit. We provide flexible plans so you can change or cancel your reservation without any monetary loss.'],
        ['question' => '3.	Do I Need Travel Insurance for My Visa Application?', 'answer' => 'Yes, most countries demand travel insurance as a prerequisite for the visa application process. Travel insurance offers financial security against medical emergencies, trip cancellations and lost luggage while you are traveling. Embassies usually demand proof of coverage that complies with certain requirements like minimum coverage amount. At WTS Visa Consultancy, we assist you in selecting the appropriate travel insurance that satisfies embassy requirements and insures you against all risks. Travel insurance provides you with a sense of security that you are safe from unplanned costs.'],
        ['question' => '4.	How Can I Get the Best Foreign Exchange Rates for My Trip?', 'answer' => 'The best exchange rates can be obtained by comparing providers and steering clear of airport exchanges where prices are more expensive. Our forex assistance service enables you to receive competitive rates with minimal transaction charges. We also track market trends to guide you on when to exchange money. We can provide pre-loaded travel cards for safe and easy spending while on your trip. We make sure you receive the best value for your money and assist you in managing your expenses while studying overseas.'],
        ['question' => '5. How Can I Use Your Travel Arrangement Services?', 'answer' => 'It is simple to use our travel arrangement services. Simply get in touch with our team and provide your travel information. We will assist you with flight reservations, hotel reservations and forex arrangements according to your visa needs. Our team will handle all the paperwork and make sure that your travel arrangements conform to embassy regulations. We also provide airport pickup and pre-travel assistance so that you are properly equipped for your travel. At WTS Visa Consultancy, we prefer your travel to be smooth and hassle-free from beginning to end.'],
    ];
@endphp

<x-faq :faqs="$faqs" />