<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UniversityController extends Controller
{
    public function index()
    {
        $universities = [
            [
                'image' => 'images/university-images/harvard-university.webp',
                "logo"=> "images/universities/harvard-logo.webp",
                'university_name' => 'Harvard University',
                'course' => 'MBA',
                'course_duration' => '2 Years',
                'course_type' => 'Postgraduate',
                'course_level_id' => 'Masters',
                'tuition_fees' => 65000,
                'location' => 'United States',
                'application_fees' => 100,
                'university_id' => 1,
                'currency_symbol' => '$',
                'currency_code' => 'USD',
            ],
            [
                'image' => 'images/university-images/university-of-cambridge.webp',
                "logo"=> "images/universities/cambridge-logo.webp",
                'university_name' => 'University of Cambridge',
                'course' => 'Computer Science',
                'course_duration' => '3 Years',
                'course_type' => 'Undergraduate',
                'course_level_id' => 'Bachelors',
                'tuition_fees' => 50000,
                'location' => 'Unied Kingdom',
                'application_fees' => 80,
                'university_id' => 2,
                'currency_symbol' => '£',
                'currency_code' => 'GBP',
            ],
            [
                'image' => 'images/university-images/maynooth-university.webp',
                'logo' => 'images/universities/maynooth-logo.webp',
                'university_name' => 'Maynooth University',
                'course' => 'MA International Development',
                'course_duration' => 'Year 1',
                'course_type' => 'Postgraduate',
                'course_level_id' => 4,
                'tuition_fees' => 13000,
                'location' => 'Maynooth',
                'application_fees' => 50,
                'university_id' => 311,
                'currency_symbol' => '€',
                'currency_code' => 'EUR',
            ],
            [
                'image' => 'images/university-images/maynooth-university.webp',
                'logo' => 'images/universities/maynooth-logo.webp',
                'university_name' => 'Maynooth University',
                'course' => 'MSc Digital Marketing',
                'course_duration' => 'Year 1',
                'course_type' => 'Postgraduate',
                'course_level_id' => 4,
                'tuition_fees' => 18000,
                'location' => 'Maynooth',
                'application_fees' => 50,
                'university_id' => 311,
                'currency_symbol' => '€',
                'currency_code' => 'EUR',
            ],
            [
                'image' => 'images/university-images/university-of-west-london.webp',
                'logo' => 'images/universities/west-london-logo.webp',
                'university_name' => 'University of West London',
                'course' => 'BA (Hons) Business Studies with Internship',
                'course_duration' => 'West London Campus',
                'course_type' => 'Undergraduate',
                'course_level_id' => 1,
                'tuition_fees' => 16250,
                'location' => 'West London Campus',
                'application_fees' => 0,
                'university_id' => 101,
                'currency_symbol' => '£',
                'currency_code' => 'GBP',
            ],
            [
                'image' => 'images/university-images/newcastle-university.webp',
                'logo' => 'images/universities/newcastle-logo.webp',
                'university_name' => 'Newcastle University',
                'course' => 'Data Science with Specialization in Statistics MSc',
                'course_duration' => 'MSc full time:12 months,(PGDip, PGCert - full time: 8 months)',
                'course_type' => 'Postgraduate',
                'course_level_id' => 4,
                'tuition_fees' => 30600,
                'location' => 'Newcastle',
                'application_fees' => 0,
                'university_id' => 91,
                'currency_symbol' => '£',
                'currency_code' => 'GBP',
            ],
            [
                'image' => 'images/university-images/durham-university.webp',
                'logo' => 'images/universities/durham-logo.webp',
                'university_name' => 'Durham University',
                'course' => 'MA - Environmental Hazards and Risk',
                'course_duration' => 'Durham City',
                'course_type' => 'Postgraduate',
                'course_level_id' => 4,
                'tuition_fees' => 28500,
                'location' => 'Durham City',
                'application_fees' => 60,
                'university_id' => 46,
                'currency_symbol' => '£',
                'currency_code' => 'GBP',
            ],
            [
                'image' => 'images/university-images/fanshawe-college.webp',
                'logo' => 'images/universities/fanshawe-logo.webp',
                'university_name' => 'Fanshawe College of Applied Arts and Technology',
                'course' => 'Computer Programming and Analysis (CPA3)',
                'course_duration' => '90 Weeks',
                'course_type' => 'Advance Diploma',
                'course_level_id' => 12,
                'tuition_fees' => 48603,
                'location' => 'London Campus',
                'application_fees' => 0,
                'university_id' => 236,
                'currency_symbol' => '$',
                'currency_code' => 'CAD',
            ],
            [
                'image' => 'images/university-images/fanshawe-college.webp',
                'logo' => 'images/universities/fanshawe-logo.webp',
                'university_name' => 'Fanshawe College of Applied Arts and Technology',
                'course' => 'Cyber Security (CYB1)',
                'course_duration' => '90 Weeks',
                'course_type' => 'Advance Diploma',
                'course_level_id' => 12,
                'tuition_fees' => 48604,
                'location' => 'London Campus',
                'application_fees' => 0,
                'university_id' => 236,
                'currency_symbol' => '$',
                'currency_code' => 'CAD',
            ],
            [
                'image' => 'images/university-images/fanshawe-college.webp',
                'logo' => 'images/universities/fanshawe-logo.webp',
                'university_name' => 'Fanshawe College of Applied Arts and Technology',
                'course' => 'Cyber Security (Co-Op) (CYBI)',
                'course_duration' => '90 weeks',
                'course_type' => 'Diploma',
                'course_level_id' => 11,
                'tuition_fees' => null,
                'location' => 'London',
                'application_fees' => 0,
                'university_id' => 236,
                'currency_symbol' => '$',
                'currency_code' => 'CAD',
            ],
            // Add more as needed
        ];

        return view('universities', compact('universities'));
    }
}
